---
- name: AWS Cloud Operations
  hosts: localhost
  gather_facts: false

  vars:
    instance_config:
      tags:
        function: cloud-ops
      key_name: app-keypair
      image_id: ami-016eb5d644c333ccb
      vpc_subnet_id: subnet-08ae1898fbd3217e5
      security_group: default
      wait: false

  tasks:
    - name: Create a key pair in us-east-1 named app-keypair
      amazon.aws.ec2_key:
        name: app-keypair
        region: us-east-1
      register: keypair
    
    - name: Create a t3.medium instance called summit-connect-01 using instance_config var
      amazon.aws.ec2_instance:
        name: summit-connect-01
        key_name: "{{ instance_config.key_name }}"
        instance_type: t3.medium
        image_id: "{{ instance_config.image_id }}"
        wait: "{{ instance_config.wait }}"
        region: us-east-1
        vpc_subnet_id: "{{ instance_config.vpc_subnet_id }}"
        security_group: "{{ instance_config.security_group }}"
        network:
          assign_public_ip: true
        tags: "{{ instance_config.tags }}"
      register: ec2
    
    