---
- name: AWS Cloud Operations
  hosts: localhost
  gather_facts: false

  vars:
    instance_config:
      tags:
        function: cloud-ops
      key_name: app-keypair
      image_id: ami-016eb5d644c333ccb
      vpc_subnet_id: subnet-08ae1898fbd3217e5
      security_group: sg-05d975910d4798cef
      wait: false

  tasks:
    # - name: Create a key pair in us-east-1 named app-keypair
    
    
    # - name: Create a t3.medium instance called summit-connect-01 using instance_config var in us-east-1 region

    
    
    
    
    
    
    
    
    